# Generated by Django 4.2.21 on 2025-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza_lab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                ("id_avaliacao", models.AutoField(primary_key=True, serialize=False)),
                ("nota_pizza", models.IntegerField()),
                ("nota_atendimento", models.IntegerField()),
                ("data_avaliacao", models.DateField()),
                ("comentario", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "avaliacao",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Compraingrediente",
            fields=[
                ("id_compra", models.AutoField(primary_key=True, serialize=False)),
                ("cnpj", models.CharField(blank=True, max_length=30, null=True)),
                ("datacompra", models.DateField()),
                (
                    "valor_ingrediente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
            ],
            options={
                "db_table": "compraingrediente",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Escalatrabalho",
            fields=[
                ("id_escala", models.AutoField(primary_key=True, serialize=False)),
                ("data_escala", models.DateField()),
                ("tipo_turno", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "escalatrabalho",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                ("id_fornecedor", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=30)),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("cnpj", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "fornecedor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TamanhoPizza",
            fields=[
                ("id_tamanho", models.AutoField(primary_key=True, serialize=False)),
                ("tamanho", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "tamanho_pizza",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoPizza",
            fields=[
                ("id_tipo", models.AutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "tipo_pizza",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
                ("email", models.CharField(max_length=133, unique=True)),
                ("cpf", models.CharField(max_length=11)),
            ],
            options={
                "db_table": "user_profile",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfileGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "user_profile_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfileUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "user_profile_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ValorPizza",
            fields=[
                ("id_valor", models.AutoField(primary_key=True, serialize=False)),
                (
                    "preco",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "db_table": "valor_pizza",
                "managed": False,
            },
        ),
    ]
