# Generated by Django 4.2.21 on 2025-06-06 20:39

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profile",
            managers=[
                ("objects", user.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
